PullRequestTargetRegexs:
  - 'main'

JiraTagging:
  ReadJira: false
  Url: ''
  GeneralPatterns:
    - 'asdsd'

Approval:
  ApprovalGroups: 
    - Name: 'Something'
      Users: 
        - 'BrianCArnold'
      Required: 1
