PullRequestTargetRegexs:
  - 'main'

JiraTagging:
  ReadJira: false
  Url: ''
  GeneralPatterns:
    - 'SPR-\\d+'

Approval:
  ApprovalGroups: 
    - Name: 'Something'
      Teams:
        - GroupB
      # Users:
      #   - SPR-Brian
      Required: 1
