PullRequestTargetRegexs:
  - 'main'

JiraTagging:
  ReadJira: false
  Url: ''
  GeneralPatterns:
    - 'asdsd'

Approval:
  ApprovalGroups: 
    - Name: 'Something'
      Users:
        - SPR-Brian
      Required: 1
