PullRequestTargetRegexs:
  - 'main'

JiraTagging:
  ReadJira: false
  Url: ''
  GeneralPatterns:
    - '(?:(?:[^\w]|^)((?:SPR|SRC|SRM|SA|DOG|BIL|CSP|NG)-[0-9]{1,}))'

Approval:
  ApprovalGroups: 
    - Name: 'Something'
      Teams:
        - GroupB
      # Users:
      #   - SPR-Brian
      Required: 1
