PullRequestTargetRegexs:
  - 'main'

JiraTagging:
  ReadJira: false
  Url: ''
  GeneralPatterns:
    - 'asdsd'

Approval:
  ApprovalGroups: 
    - Name: 'Something'
      Teams:
        - GroupB
      Required: 1
