name: SimpleWorkflow

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - 'main'
jobs:
  Task:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"